#! /bin/bash

# curl -o setupHost https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Base/setupBaxe && bash setupBase

# Get Base scripts
curl -o ~/.bashrc                  https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Base/script/bashrc
curl -o /usr/local/bin/hg          https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Base/script/hg
curl -o /usr/local/bin/hi5         https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Base/script/hi5
curl -o /usr/local/bin/lt          https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Base/script/lt
curl -o /usr/local/bin/update      https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Base/script/update

mkdir -p /etc/ssmtp

# Get Base config files
curl -o /etc/apt/apt.conf.d/20auto-upgrades       https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Host/conf/20auto-upgrades
curl -o /etc/apt/apt.conf.d/50unattended-upgrades https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Host/conf/50unattended-upgrades
curl -o cronjobs                                  https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Host/conf/cronjobs
curl -o /etc/ssmtp/revaliases                     https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Host/conf/revaliases
curl -o /etc/ssmtp/ssmtp.conf                     https://raw.githubusercontent.com/Martech-WorkShop/toolBelt/Prod/Host/conf/ssmtp.conf

# Add the executable flag to scrips
chmod +x /usr/local/bin/hg
chmod +x /usr/local/bin/hi5
chmod +x /usr/local/bin/lt
chmod +x /usr/local/bin/update

# You send a test email with:
# echo -e 'Subject: Hello there!\n\nDoing good here, how are you doing?' | sendmail -vvv your@email.com
